apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
  {{- include "voting-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.type }}
  selector:
    app: db
  {{- include "voting-app-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.db.ports | toYaml | nindent 2 -}}