apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-app-chart.fullname" . }}-redis
  labels:
    app: redis
  {{- include "voting-app-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
    {{- include "voting-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: redis
      {{- include "voting-app-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.redis.redis.image.repository }}:{{ .Values.redis.redis.image.tag
          | default .Chart.AppVersion }}
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - emptyDir: {}
        name: redis-data