apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-app-chart.fullname" . }}-result
  labels:
    app: result
  {{- include "voting-app-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.result.replicas }}
  selector:
    matchLabels:
      app: result
    {{- include "voting-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: result
      {{- include "voting-app-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.result.result.image.repository }}:{{ .Values.result.result.image.tag
          | default .Chart.AppVersion }}
        name: result
        ports:
        - containerPort: 80
          name: result
        resources: {}